sudo: false
language: php

php:
  - 5.6
  - 7.1

cache:
  directories:
    - $HOME/.composer/cache


env:
    global:
        - MIN_PHP=5.5.9

cache:
    directories:
        - .phpunit

before_install:
  - if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - travis_retry composer self-update
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then composer require --dev --no-update satooshi/php-coveralls ; fi

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs

script:
  - vendor/bin/phpcs --standard=PSR2 ./src